from slack_sdk import WebClient
from slack_sdk.errors import SlackApiError
from config.settings import settings


def _get_emoji_prefix(message: str) -> str:
    msg_lower = message.lower()
    if "flagged" in msg_lower or "risk" in msg_lower:
        return "[ALERT]"
    elif "approved" in msg_lower or "complete" in msg_lower:
        return "[OK]"
    elif "pending" in msg_lower or "review" in msg_lower:
        return "[PENDING]"
    return "[INFO]"


def send_alert(message: str, channel_id: str = None) -> dict:
    target_channel = channel_id or settings.slack_channel_id
    emoji = _get_emoji_prefix(message)
    formatted_message = f"{emoji} {message}"
    print(f"[Slack] Sending alert to {target_channel}: {formatted_message[:80]}...")

    try:
        client = WebClient(token=settings.slack_bot_token, timeout=5)
        response = client.chat_postMessage(
            channel=target_channel,
            text=formatted_message,
        )
        print(f"[Slack] Alert sent successfully. ts={response['ts']}")
        return {"status": "sent", "channel": target_channel, "ts": response["ts"]}
    except SlackApiError as e:
        error_msg = f"[Slack] Slack API error: {e.response['error']}"
        print(error_msg)
        raise RuntimeError(error_msg)
    except Exception as e:
        error_msg = f"[Slack] Failed to send alert: {str(e)}"
        print(error_msg)
        raise RuntimeError(error_msg)


def send_ops_report(report_data: dict) -> dict:
    print(f"[Slack] Sending ops report to {settings.slack_channel_id}")
    try:
        client = WebClient(token=settings.slack_bot_token, timeout=5)

        blocks = [
            {
                "type": "header",
                "text": {
                    "type": "plain_text",
                    "text": "📊 OmniForce Ops Report",
                    "emoji": True,
                },
            },
            {"type": "divider"},
        ]

        for key, value in report_data.items():
            blocks.append(
                {
                    "type": "section",
                    "fields": [
                        {
                            "type": "mrkdwn",
                            "text": f"*{key}*\n{value}",
                        }
                    ],
                }
            )

        blocks.append({"type": "divider"})
        blocks.append(
            {
                "type": "context",
                "elements": [
                    {
                        "type": "mrkdwn",
                        "text": "Generated by OmniForce AI Workforce | Ops Agent",
                    }
                ],
            }
        )

        response = client.chat_postMessage(
            channel=settings.slack_channel_id,
            blocks=blocks,
            text="OmniForce Ops Report",
        )
        print(f"[Slack] Ops report sent. ts={response['ts']}")
        return {"status": "sent", "channel": settings.slack_channel_id, "ts": response["ts"]}
    except SlackApiError as e:
        error_msg = f"[Slack] Slack API error sending report: {e.response['error']}"
        print(error_msg)
        raise RuntimeError(error_msg)
    except Exception as e:
        error_msg = f"[Slack] Failed to send ops report: {str(e)}"
        print(error_msg)
        raise RuntimeError(error_msg)
